### PR TITLE
Solution to issue #1011

### PR DESCRIPTION
**Pull request by Zensey**
Solution to issue #1011

### CODE REVIEW

**Comment by iuriifavi** [comment]
Problem is still exist with this fix.

**Comment by Zensey** [comment]
What 
hardware, NodeJS version, Operating System do you use ?

Can you please add `printf("errorCode %i\n", data->errorCode);` before switch operator and reproduce the problem ?

**Comment by iuriifavi** [comment]
I dont see any error code.
System: Windows 10, Node.JS v7.2.0, PL2303 USB2COM.
If i'm unplug usb it's throw exception:
 Caught exception: TypeError: undefined is not a function.

Problem exist only on Window, on Mac everything is fine.
Thanks

**Comment by Zensey** [comment]
@iuriifavi,
I'm Sorry, I have no PL2303, so it would be great, if you supply me with logs.
Please take the following C code and replace  EIO_WatchPort in `src/serialport_win.cpp`  with it, 
then make `npm install --build-from-source`,
then run test and reproduce problem.

Also NtTace logs can be helpful. You can take them this way:
```
c:\Portable\NtTrace\NtTrace.exe node test > log.txt
````

```
void EIO_WatchPort(uv_work_t* req) {
  WatchPortBaton* data = static_cast<WatchPortBaton*>(req->data);
  data->bytesRead = 0;
  data->disconnected = false;

  // Event used by GetOverlappedResult(..., TRUE) to wait for incoming data or timeout
  // Event MUST be used if program has several simultaneous asynchronous operations
  // on the same handle (i.e. ReadFile and WriteFile)
  HANDLE hEvent = CreateEvent(NULL, TRUE, FALSE, NULL);

  while (true) {
    OVERLAPPED ov = {0};
    ov.hEvent = hEvent;

    // Start read operation - synchrounous or asynchronous
    DWORD bytesReadSync = 0;
    if (!ReadFile((HANDLE)data->fd, data->buffer, bufferSize, &bytesReadSync, &ov)) {
      data->errorCode = GetLastError();
      printf("data->errorCode %i\n", data->errorCode);
      fflush(stdout);
      if (data->errorCode != ERROR_IO_PENDING) {
        // Read operation error
        if (data->errorCode == ERROR_OPERATION_ABORTED || data->errorCode == ERROR_ACCESS_DENIED) {
          data->disconnected = true;
        } else {
          ErrorCodeToString("Reading from COM port (ReadFile)", data->errorCode, data->errorString);
          CloseHandle(hEvent);
          return;
        }
        break;
      }

      // Read operation is asynchronous and is pending
      // We MUST wait for operation completion before deallocation of OVERLAPPED struct
      // or read data buffer

      // Wait for async read operation completion or timeout
      DWORD bytesReadAsync = 0;
      if (!GetOverlappedResult((HANDLE)data->fd, &ov, &bytesReadAsync, TRUE)) {
        // Read operation error
        data->errorCode = GetLastError();
        printf("!GetOverlappedResult data->errorCode %i\n", data->errorCode);
        fflush(stdout);
        if (data->errorCode == ERROR_OPERATION_ABORTED || data->errorCode == ERROR_ACCESS_DENIED) {
          printf("disconnected=true\n", data->errorCode);
          fflush(stdout);
          data->disconnected = true;
        } else {
          ErrorCodeToString("Reading from COM port (GetOverlappedResult)", data->errorCode, data->errorString);
          CloseHandle(hEvent);
          return;
        }
        break;
      } else {
        // Read operation completed asynchronously
        data->bytesRead = bytesReadAsync;
      }
    } else {
      // Read operation completed synchronously
      data->bytesRead = bytesReadSync;
    }

    // Return data received if any
    if (data->bytesRead > 0) {
      break;
    }
  }
  printf("exit while \n");
  fflush(stdout);
  CloseHandle(hEvent);
}
```

**Comment by Zensey** [comment]
If somebody has PL2303, your help is still needed

**Comment by iuriifavi** [comment]
I'm not have access to it for 1 week. I will do testing soon.

Best Regards
Iurii Favi

**Pull request closed without merging**
